Encoding:
  Enabled: false

LineLength:
  Max: 1000

# The default 10 lines limit is unrealistic.
MethodLength:
  Max: 50

BlockNesting:
  Max: 5

# Lining up the attributes of some methods is advantageous for readability
SpaceBeforeFirstArg:
  Enabled: false
