language: ruby
bundler_args: "--without kitchen_vagrant"
rvm:
- 2.1
before_install:
- openssl aes-256-cbc -K $encrypted_a3e58ce98bf2_key -iv $encrypted_a3e58ce98bf2_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mkdir .chef ~/.chef
- mv .ssh/travis_ci_ec2.pem ~/.ssh/travis_ci_ec2.pem
- mv .ssh/travis_github ~/.ssh/id_rsa
- mv .ssh/trubot.pem ~/.chef/trubot.pem
- echo 'node_name "trubot"' >> ~/.chef/knife.rb
- echo 'client_key "~/.chef/trubot.pem"' >> ~/.chef/knife.rb
- echo 'chef_server_url "https://api.opscode.com/organizations/evertrue"' >> ~/.chef/knife.rb
- chmod 600 ~/.chef/knife.rb ~/.chef/trubot.pem
- chmod 600 ~/.ssh/travis_ci_ec2.pem ~/.ssh/id_rsa
- ssh-add -D
install:
- bundle install --without vagrant
- bundle exec berks install
script:
- bundle exec rake travis
after_script:
- bundle exec rake integration:cloud_destroy
notifications:
  slack:
    secure: L6rkaxJIbxBEU/9Kt2YGl58roU2ics1uN8F/KaGmf2JUt/N3v9b2u5fbAhOZctcSDELXRorrLKFdddI0WB+VmUBkkZEMXuSXDSHhr9jKRNUrVH/0a/MULTp2sEhI6dyyHdWJqaqWcHj7m0oze8k4y97WeE5Bx/+HBiE26JsTjiM=
