language: ruby
bundler_args: "--without kitchen_vagrant"
rvm:
- 2.1
before_install:
- openssl aes-256-cbc -K $encrypted_a3e58ce98bf2_key -iv $encrypted_a3e58ce98bf2_iv
  -in travis_ci_ec2.pem.enc -out ~/.ssh/travis_ci_ec2.pem -d
- mkdir ~/.chef
- echo 'node_name "trubot"' >> ~/.chef/knife.rb
- chmod 600 ~/.chef/knife.rb ~/.ssh/travis_ci_ec2.pem
install:
- bundle install --without vagrant
- bundle exec berks install
script:
- bundle exec rake travis
after_script:
- bundle exec rake integration:cloud_destroy
notifications:
  slack:
    secure: L6rkaxJIbxBEU/9Kt2YGl58roU2ics1uN8F/KaGmf2JUt/N3v9b2u5fbAhOZctcSDELXRorrLKFdddI0WB+VmUBkkZEMXuSXDSHhr9jKRNUrVH/0a/MULTp2sEhI6dyyHdWJqaqWcHj7m0oze8k4y97WeE5Bx/+HBiE26JsTjiM=
