# .bash_profile

# DO NOT EDIT THIS FILE ON A DEPLOYED HOST.
#
# This file is managed by Chef.
#

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.{path,bash_prompt,exports,aliases,functions}; do
  [ -r "$file" ] && source "$file"
done
unset file

for script in ~/.extras.d/* ; do
  if [ -r $script ] ; then
    . $script
  fi
done
